### ISSUE TITLE
Pb with Fields unicity

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/genericobject#16]
If a generic object can use 'Fields unicity', one can create a fields unicity check (Setup > Checks).
Let's say that the generic object has only the 6 fields by default + Domain.
Then in the fields unicity check definition, Domain is displayed TWICE in the list of unique fields. Indeed, Domain is displayed in place of Name.
Save with the 1st occurence of Domain -> name is saved in table glpi_fieldunicities, column fields.
Save with the 2nd occurence of Domain -> domain is saved in db.

Same pb with Manufacturer

**Comment by blerohellec** [comment]
Another thing : I add fields to a genericobject, and at a time, one field disappears from the 'unique fields' list in the unicity check.

Create a 'test' genericobject : it has 6 fields by default (2 appears in the 'unique fields' list).
add the following fields to the genericobject
- alternate username
- alternate username number
- creation date
- expiration date
- group
- group in charge
- managemnet type
- item location
Till this point, everything's OK
Now, add 'Inventory number' -> 'item location' has disappeared from the 'unique fields' list in Setup > Check.

Notice : I'm running version 2.3.2

**Comment by wawax** [comment]
I'll try to take a look soon, but I'd rather do it after the 0.85+1.0 release.

**Comment by btry** [comment]
This bug may need a fix in GLPI, in the call hierarchy of FieldUnicity::dropdownFields()

**Comment by trasher** [comment]
Hello, Is that problem solved?

**Comment by btry** [comment]
Hi

I still reproduce on GLPi 0.90

![image](https://cloud.githubusercontent.com/assets/14139801/19201332/92d14cd0-8ccd-11e6-9351-d729f2d62ad9.png)

**Comment by btry** [comment]
FieldUnicity::dropdownFields() works well for similar cases with itemtypes from GLPi core, like Computer.

I found the problem is in t he search options the plugin generates for its own itemtypes. It always an entry 'linkfield'. This property of search option should exist only when the foreign key does not matches the name of the itemtype

For example : 
computing the plural of Domain and adding the suffix _id matches the itemtype Domain
computing the plutal of users_id_tech and adding the suffix _id does not match any itemtype. In such case, linkfield is needed.

When linkfield is present when it is not needed, CommonDBTM::getSearchOptionByField() (called by 
FieldUnicity::dropdownFields() ) does not work properly.

**Comment by btry** [comment]
PR #111 is an attempt to fix this issue.

In addition to the previous comment, the order of search options is very important to ensure tne name of the object is available for unicity.

**Comment by btry** [comment]
Hi

Ping ? 
@trasher , @blerohellec I would appreciate you validate / test this patch.

**Comment by trasher** [comment]
Hello,

I'm OK with the changes, the PR is not reviewed since I do not have time to test that right now; I'll try to take a closer look next week :)

**Comment by trasher** [comment]
Fixed from #111
