### ISSUE TITLE
Object not display good

### ISSUE THREAD

**Issue by CrysyP** [pluginsGLPI/genericobject#241]
Hi all,

I create object catégorie and  2 objects.
But :
There not display good
There not display on element when i create a ticket.
You can see the pics there 
https://forum.glpi-project.org/viewtopic.php?id=168809
![Capt](https://user-images.githubusercontent.com/49651254/56215942-cb924b00-6060-11e9-908b-cdc5ff24efea.png)
![Cap3](https://user-images.githubusercontent.com/49651254/56215951-d2b95900-6060-11e9-8658-d90f6394625f.PNG)
![Cap2](https://user-images.githubusercontent.com/49651254/56215966-d8af3a00-6060-11e9-99bb-a06ccac202ad.PNG)

Can you help me plz ?
Crysy

**Comment by cedric-anne** [comment]
Hi,

1) The list is incorectly displayed due to the fact that your object "class" contains a number (i.e. `Capteur220v4g`). 9.4 version of GLPI is more strict for itemtype and does not accept anymore numbers in them. A fix has been proposed in `fields` plugin (see https://github.com/pluginsGLPI/fields/pull/306), and similar fix should be done for `genericobject` plugin, but it requires some work.

2) The fact that you do not see this type of items in the ticket form is due to a bad configuration. See https://github.com/pluginsGLPI/genericobject/issues/199 .

Regards
